zuul:
  # allows forwarding of the authorization header and cookies
  sensitiveHeaders:

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

auth0:
  clientId: xXz4FrF4u9ryX0SbonX0Nge2Q2QrKR4S
  clientSecret: ENC(mLSmr+RX29yAKUKLPoUwiXhqJizgpqF3TEV4MHzLSSsrJsGP9+ToBXtzW7GHOT93FgkV519CS5uVem1RWPQNafF3t2fGbj7gPxE6tofMg60=)
  audience: https://blakehowe96.au.auth0.com/api/v2/
  domain: blakehowe96.au.auth0.com
  issuer: https://blakehowe96.au.auth0.com/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000