zuul:
  # allows forwarding of the authorization header
  sensitiveHeaders: Cookie,Set-Cookie

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

auth0:
  clientId: xXz4FrF4u9ryX0SbonX0Nge2Q2QrKR4S
  clientSecret: ENC(mLSmr+RX29yAKUKLPoUwiXhqJizgpqF3TEV4MHzLSSsrJsGP9+ToBXtzW7GHOT93FgkV519CS5uVem1RWPQNafF3t2fGbj7gPxE6tofMg60=)
  audience: https://blakehowe96.au.auth0.com/api/v2/
  domain: blakehowe96.au.auth0.com